# Autogenerated from python.template file

from quixstreams import Application
from quixstreams.models import TopicConfig
import seaborn as sns

from river import metrics, preprocessing
from river import anomaly
import matplotlib.pyplot as plt
from river import ensemble
from river import optim
from sklearn.metrics import confusion_matrix
from river import compose
from river import preprocessing
import json

import dill
import numpy as np


# Define an application that will connect to Kafka
app = Application(
    broker_address="localhost:39092",  # Kafka broker address
    auto_offset_reset="earliest",
    consumer_group="halfSpaceTree",
)

# Define the Kafka topics
input_topic = app.topic("anomaly-pred", value_deserializer="json")

# Create a Streaming DataFrame connected to the input Kafka topic
sdf = app.dataframe(topic=input_topic)


# Define River Model
model = (

    anomaly.HalfSpaceTrees(

        n_trees=5,
        height=3,
        window_size=3,
        seed=42,

    ))


# Define new features


# Drop features


# Function for training the model
def train_and_predict(X):

    model.learn_one(X)

    y_predicted = model.score_one(X)

    print(y_predicted)

    with open('HalfSpaceTrees.pkl', 'wb') as model_file:
        dill.dump(model, model_file)

    return X


# Apply the train_and_predict function to each row in the filtered DataFrame
sdf = sdf.apply(train_and_predict)

# Run the streaming application (app automatically tracks the sdf!)
app.run()

# %%
with open('../../HalfSpaceTrees.pkl', 'rb') as model_file:
    model = dill.load(model_file)
# %%
X = [0.5, 0.45, 0.43, 0.44, 0.445, 0.45, 0.0]
for x in X:
    features = {'x': x}
    print(
        f'Anomaly score for x={x:.3f}: {model.score_one(features):.3f}')
    # model.learn_one(features)

# %%
model.__dict__

# %%
